ds:
  path: './data/birds'
  extensions: ['.png', '.jpg', '.jpeg', '.webp']
  loader_worker_count: 6

img:
  size: 64
  channels: 3

tr:
  use_fp16: true
  dynamic_loss_period: 500
  learning_rate: 0.0002
  learning_rate_warmup_steps: 500
  weight_decay: 0.0
  gradient_clipping: 1.0
  gradient_accumulation_steps: 1
  batch_size: 32
  ema_alpha: 0.99
  yield_freq: 10
  save_freq: 1_000
  save_checkpoint_freq: 10_000
  wandb:
    img_freq: 250
    img_n: 8
    img_steps: 64
    img_eta: 0.5
    img_clip_percentile: 0.995
    project: 'Kigo-2'
    group: 'Dev'
    name: null
    tags: ['deleteme']


model:
  blocks:
    - channels: 64
      blocks: 2
      groupnorm_groups: 8
      attention_heads: 0
      attention_head_channels: 0
      dropout: 0.1
    - channels: 128
      blocks: 2
      groupnorm_groups: 8
      attention_heads: 0
      attention_head_channels: 0
      dropout: 0.1
    - channels: 256
      blocks: 2
      groupnorm_groups: 8
      attention_heads: 0
      attention_head_channels: 0
      dropout: 0.1
    - channels: 256
      blocks: 2
      groupnorm_groups: 8
      attention_heads: 4
      attention_head_channels: 32
      dropout: 0.1
  outer_groupnorm_groups: 8
  outer_channels: 32
  output_channels: 3
  input_channels: 3
  snr_sinusoidal_embedding_width: 32
  snr_embedding_width: 32
